//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalartsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.comentario = new HashSet<comentario>();
        }
    
        public int id_post { get; set; }
        public int id_usuario { get; set; }
        public int id_tipo_post { get; set; }
        public string foto_url { get; set; }
        public double precio { get; set; }
        public string localizacion { get; set; }
        public string ciudad { get; set; }
        public string direccion { get; set; }
        public string titulo_post { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public int likes { get; set; }
        public Nullable<System.Guid> guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Newtonsoft.Json.JsonIgnore] public virtual ICollection<comentario> comentario { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual usuario usuario { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual tipo_post tipo_post { get; set; }
    }
}
