//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalartsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.post = new HashSet<post>();
        }
    
        public int id_usuario { get; set; }
        public int id_persona { get; set; }
        public int id_tipo_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string contrasena { get; set; }
        public string arte_tipo { get; set; }
        public System.Guid guid { get; set; }
    
        [Newtonsoft.Json.JsonIgnore] public virtual persona persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Newtonsoft.Json.JsonIgnore] public virtual ICollection<post> post { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
